from app.schemas import Problem

PROBLEMS: list[Problem] = [
    Problem(
        id="url-shortener",
        title="Design a URL Shortener",
        company_style="Bitly / TinyURL",
        difficulty="Easy",
        duration_min=35,
        prompt="Design a service like bit.ly that turns long URLs into short links and redirects users quickly at global scale.",
        functional=[
            "Create a short URL from a long URL",
            "Redirect short URL to original URL",
            "Optional custom aliases and expiry",
            "Basic analytics: click count",
        ],
        non_functional=[
            "100M new URLs/day, 10:1 read/write",
            "Redirect P99 < 50ms",
            "High availability, links never silently break",
        ],
        deep_dives=["Hash vs base62 ID generation", "Caching hot keys", "Analytics pipeline"],
        starter_hint="Start with write path, read path, and how you generate unique short codes.",
    ),
    Problem(
        id="twitter",
        title="Design Twitter / X",
        company_style="Twitter / X",
        difficulty="Hard",
        duration_min=45,
        prompt="Design a social network where users post short messages, follow others, and see a home timeline.",
        functional=[
            "Post a tweet",
            "Follow / unfollow",
            "Home timeline of followees",
            "User profile timeline",
        ],
        non_functional=[
            "500M users, 200M DAU",
            "Fan-out on write vs read tradeoff",
            "Timeline load < 200ms",
        ],
        deep_dives=["Celebrity fan-out", "Ranking", "Search"],
        starter_hint="Clarify timeline semantics first: chronological vs ranked, and who is a celebrity.",
    ),
    Problem(
        id="whatsapp",
        title="Design WhatsApp",
        company_style="Meta",
        difficulty="Hard",
        duration_min=45,
        prompt="Design a 1:1 and group messaging system with delivery receipts, media, and presence.",
        functional=[
            "1:1 chat and group chat",
            "Online/offline and last-seen",
            "Media messages",
            "Read receipts",
        ],
        non_functional=["End-to-end encryption awareness", "Billions of messages/day", "Low latency on mobile"],
        deep_dives=["WebSocket vs long poll", "Message queues per user", "Group fan-out"],
        starter_hint="Walk through a message from sender phone to recipient phone, including offline case.",
    ),
    Problem(
        id="youtube",
        title="Design YouTube",
        company_style="Google",
        difficulty="Hard",
        duration_min=50,
        prompt="Design a video platform for upload, transcoding, playback, comments, and recommendations.",
        functional=["Upload video", "Adaptive bitrate playback", "Comments", "Subscriptions"],
        non_functional=["CDN for video", "Petabyte storage", "Watch-time ranking"],
        deep_dives=["Transcoding pipeline", "Chunked streaming", "Thumbnail generation"],
        starter_hint="Separate upload/processing from playback. CDN is the star of the read path.",
    ),
    Problem(
        id="uber",
        title="Design Uber",
        company_style="Uber",
        difficulty="Hard",
        duration_min=50,
        prompt="Design a ride-hailing system: matching riders to nearby drivers, live location, and trip lifecycle.",
        functional=["Request ride", "Match driver", "Live ETA", "Payments"],
        non_functional=["Geo queries at city scale", "Matching under 10s", "Location updates every few seconds"],
        deep_dives=["Geohash / quadtree", "Matching service", "Surge"],
        starter_hint="Focus on location indexing and the matching loop before payments.",
    ),
    Problem(
        id="rate-limiter",
        title="Design a Rate Limiter",
        company_style="Stripe / Cloudflare",
        difficulty="Medium",
        duration_min=30,
        prompt="Design a distributed rate limiter used in front of public APIs.",
        functional=["Limit by API key / IP / user", "Configurable windows", "Return retry-after"],
        non_functional=["Very low overhead", "Accurate enough across many servers", "Works in multiple DCs"],
        deep_dives=["Token bucket vs sliding window", "Redis", "Race conditions"],
        starter_hint="Pick an algorithm and explain why it fits API gateways, then make it distributed.",
    ),
    Problem(
        id="news-feed",
        title="Design a News Feed",
        company_style="Facebook / Instagram",
        difficulty="Hard",
        duration_min=45,
        prompt="Design a feed of posts from friends with ranking, pagination, and near-real-time updates.",
        functional=["Publish post", "Fetch feed", "Like / comment"],
        non_functional=["Hundreds of millions of DAU", "Feed load fast", "Eventual consistency OK"],
        deep_dives=["Push vs pull", "Ranking features", "Fan-out service"],
        starter_hint="Define feed freshness vs cost, then choose push, pull, or hybrid.",
    ),
    Problem(
        id="notification",
        title="Design a Notification System",
        company_style="Slack / LinkedIn",
        difficulty="Medium",
        duration_min=35,
        prompt="Design a system that sends push, email, and in-app notifications with preferences and retries.",
        functional=["Trigger from events", "Channel routing", "User preferences", "Retries / DLQ"],
        non_functional=["High throughput", "At-least-once with idempotency", "Quiet hours"],
        deep_dives=["Priority queues", "Template service", "Provider failover"],
        starter_hint="Start with event → enqueue → worker → provider, then add preferences and failure handling.",
    ),
    Problem(
        id="web-crawler",
        title="Design a Web Crawler",
        company_style="Google",
        difficulty="Medium",
        duration_min=40,
        prompt="Design a polite, scalable web crawler that discovers URLs and stores page content.",
        functional=["URL frontier", "Fetch + parse", "robots.txt", "Dedup"],
        non_functional=["Billions of pages", "Politeness per host", "Freshness"],
        deep_dives=["Priority frontier", "DNS cache", "Canonicalization"],
        starter_hint="The URL frontier and politeness queues are the heart of the design.",
    ),
    Problem(
        id="autocomplete",
        title="Design Search Autocomplete",
        company_style="Google / Amazon",
        difficulty="Medium",
        duration_min=35,
        prompt="Design typeahead suggestions as a user types a search query.",
        functional=["Top-k suggestions per prefix", "Personalization optional", "Typo tolerance optional"],
        non_functional=["P99 < 50ms", "High QPS", "Frequently updated rankings"],
        deep_dives=["Trie vs n-gram", "Caching", "Offline aggregation of query logs"],
        starter_hint="Optimize for prefix lookup latency first; ranking can be precomputed offline.",
    ),
]


def get_problem(problem_id: str) -> Problem | None:
    return next((p for p in PROBLEMS if p.id == problem_id), None)
